# Generated by Django 6.0.3 on 2026-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_document_upload',
            field=models.BooleanField(default=True, help_text='If checked, this category can receive documents.'),
        ),
    ]
