# Generated by Django 6.0.3 on 2026-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_category_allow_document_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.TextField(blank=True, help_text='A brief summary of the document, searchable.'),
        ),
    ]
