# Generated by Django 6.0.3 on 2026-03-16 02:58

import json
import os
from django.db import migrations
from django.conf import settings

def setup_google_app(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # Ensure Site ID '1' exists and is set correctly
    domain = 'localhost:8000'
    site, created = Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={'domain': domain, 'name': 'SITAMPAN Local'}
    )

    # Read the gdrive.json file
    gdrive_path = os.path.join(settings.BASE_DIR, 'gdrive.json')
    try:
        with open(gdrive_path, 'r') as f:
            data = json.load(f)
            client_id = data.get('installed', {}).get('client_id', '')
            client_secret = data.get('installed', {}).get('client_secret', '')
    except (FileNotFoundError, json.JSONDecodeError):
        # Fallback to token.json if gdrive.json is not structured as expected
        token_path = os.path.join(settings.BASE_DIR, 'token.json')
        try:
             with open(token_path, 'r') as f:
                data = json.load(f)
                client_id = data.get('client_id', '')
                client_secret = data.get('client_secret', '')
        except (FileNotFoundError, json.JSONDecodeError):
            print("Warning: Could not read Google credentials from gdrive.json or token.json")
            return

    if not client_id or not client_secret:
         print("Warning: Google client_id or client_secret missing from credentials files.")
         return

    # Create or update the Google SocialApp
    google_app, created = SocialApp.objects.update_or_create(
        provider='google',
        name='Google Auth',
        defaults={
            'client_id': client_id,
            'secret': client_secret,
            'key': ''
        }
    )
    
    # Associate the SocialApp with the current Site
    google_app.sites.add(site)

def remove_google_app(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    SocialApp.objects.filter(provider='google').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file'),
        ('sites', '0002_alter_domain_unique'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(setup_google_app, remove_google_app)
    ]
