# Generated by Django 6.0.3 on 2026-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_setup_google_social_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#2563eb', help_text='Hex color code for primary theme', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
