# Generated by Django 6.0.3 on 2026-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the PDF is password protected'),
        ),
    ]
