# Generated by Django 6.0.3 on 2026-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
