# Generated by Django 6.0.3 on 2026-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_encrypted_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_syncing',
            field=models.BooleanField(default=False, help_text='Whether the document is currently syncing with Drive'),
        ),
    ]
