# Generated by Django 6.0.3 on 2026-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_is_syncing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_pdf_password',
            field=models.CharField(blank=True, help_text='Default password for locking PDFs', max_length=255, null=True),
        ),
    ]
